FROM allennlp/allennlp:v0.9.0
WORKDIR /eqasc
COPY allennlp_reasoning_explainqa /eqasc/allennlp_reasoning_explainqa

# ./metrics.json
# ./environment.yml
# ./allennlp_reasoning_explainqa/evaluator/constants.py
# ./allennlp_reasoning_explainqa/evaluator/prepare_evaluator_data.py
# ./allennlp_reasoning_explainqa/evaluator/evaluator.py
# ./allennlp_reasoning_explainqa/training/metrics/explanation_eval.py
# ./allennlp_reasoning_explainqa/training/metrics/confusion_matrix.py
# ./allennlp_reasoning_explainqa/common/constants.py
# ./allennlp_reasoning_explainqa/common/utils.py
# ./allennlp_reasoning_explainqa/model/bert_chain_clf.py
# ./allennlp_reasoning_explainqa/model/interactive.py
# ./allennlp_reasoning_explainqa/model/analyze_eqasc_perturbed.py
# ./allennlp_reasoning_explainqa/model/retrieval.py
# ./allennlp_reasoning_explainqa/data/analysis/grc_transformation.py
# ./allennlp_reasoning_explainqa/data/analysis/entity_detection.py
# ./allennlp_reasoning_explainqa/data/dataset_reader/qasc_chains_reader.py
# ./Dockerfile
# ./README.md
# ./configs/grcfinal.json
# ./configs/normalfinal.json
# ./scripts/grc.sh
# ./scripts/retrieval.sh
# ./scripts/clf.sh
# ./predictions/grc.test.predict
